language: go
sudo: false

go:
  - "1.13"

before_install:
  - go version
  - go get golang.org/x/tools/cmd/goimports

install:
  - go build ./cmd/...

script:
  - go vet ./cmd/...
  - diff <(goimports -d .) <(printf "")

